/**
 * Generate missing General Punctuation .glyph files (U+2000–U+206F) for Sergamon font.
 *
 * Checks which codepoints already exist (in punctuation/ or symbols/) and generates
 * only the missing ones into glyphs/punctuation/.
 */

import fs from "node:fs";
import path from "node:path";

const PROJECT_ROOT = path.resolve(
  path.dirname(new URL(import.meta.url).pathname),
  "..",
);
const OUTPUT_DIR = path.join(PROJECT_ROOT, "glyphs", "punctuation");
const GLYPHS_ROOT = path.join(PROJECT_ROOT, "glyphs");

const COLS = 8;
const ROWS = 16;

// Helper: convert an array of hex row values (MSB=leftmost) to a grid
function hexToGrid(hexRows: number[]): boolean[][] {
  const grid: boolean[][] = [];
  for (let r = 0; r < ROWS; r++) {
    const row: boolean[] = [];
    const val = r < hexRows.length ? hexRows[r] : 0;
    for (let c = 0; c < COLS; c++) {
      row.push(((val >> (7 - c)) & 1) === 1);
    }
    grid.push(row);
  }
  return grid;
}

// Helper: create an empty (all dots) grid
function emptyGrid(): boolean[][] {
  return hexToGrid([]);
}

interface GlyphDef {
  codepoint: number;
  name: string;
  grid: boolean[][];
}

// Define all codepoints in U+2000-U+206F with their designs
const glyphDefs: GlyphDef[] = [
  // === Zero-width and invisible characters (empty grids) ===
  { codepoint: 0x200B, name: "zerowidthspace", grid: emptyGrid() },
  { codepoint: 0x200C, name: "zerowidthnonjoiner", grid: emptyGrid() },
  { codepoint: 0x200D, name: "zerowidthjoiner", grid: emptyGrid() },
  { codepoint: 0x200E, name: "lefttorightmark", grid: emptyGrid() },
  { codepoint: 0x200F, name: "righttoleftmark", grid: emptyGrid() },

  // === Line/paragraph separators (invisible) ===
  { codepoint: 0x2028, name: "lineseparator", grid: emptyGrid() },
  { codepoint: 0x2029, name: "paragraphseparator", grid: emptyGrid() },

  // === Bidi formatting characters (invisible) ===
  { codepoint: 0x202A, name: "lefttorightembedding", grid: emptyGrid() },
  { codepoint: 0x202B, name: "righttoleftembedding", grid: emptyGrid() },
  { codepoint: 0x202C, name: "popdirectionalformatting", grid: emptyGrid() },
  { codepoint: 0x202D, name: "lefttorightoverride", grid: emptyGrid() },
  { codepoint: 0x202E, name: "righttoleftoverride", grid: emptyGrid() },

  // === U+203F UNDERTIE ===
  // A curved tie below, connecting two items
  {
    codepoint: 0x203F,
    name: "undertie",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x81, // X......X
      0x42, // .X....X.
      0x3C, // ..XXXX..
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+2054 INVERTED UNDERTIE ===
  // A curved tie above
  {
    codepoint: 0x2054,
    name: "invertedundertie",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x3C, // ..XXXX..
      0x42, // .X....X.
      0x81, // X......X
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+2055 FLOWER PUNCTUATION MARK ===
  // A small flower/asterisk-like mark
  {
    codepoint: 0x2055,
    name: "flowerpunctuationmark",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x18, // ...XX...
      0x7E, // .XXXXXX.
      0x3C, // ..XXXX..
      0x66, // .XX..XX.
      0x66, // .XX..XX.
      0x3C, // ..XXXX..
      0x18, // ...XX...
      0x18, // ...XX...
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+2057 QUADRUPLE PRIME ===
  // Four prime marks
  {
    codepoint: 0x2057,
    name: "quadrupleprime",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0xDB, // XX.XX.XX (was 0x99 but need 4 primes in 8px)
      0xDB, // XX.XX.XX
      0x6D, // .XX.XX.X (shifted down-left for slant -- actually let's do simple)
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+2058 FOUR DOT PUNCTUATION ===
  {
    codepoint: 0x2058,
    name: "fourdotpunctuation",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x24, // ..X..X..
      0x00, // ........
      0x00, // ........
      0x24, // ..X..X..
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+2059 FIVE DOT PUNCTUATION ===
  {
    codepoint: 0x2059,
    name: "fivedotpunctuation",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x24, // ..X..X..
      0x00, // ........
      0x18, // ...XX...
      0x00, // ........
      0x24, // ..X..X..
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+205A TWO DOT PUNCTUATION ===
  // Two dots stacked vertically (like colon but in general punctuation)
  {
    codepoint: 0x205A,
    name: "twodotpunctuation",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x18, // ...XX...
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x18, // ...XX...
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+205B FOUR DOT MARK ===
  // Four dots in diamond pattern
  {
    codepoint: 0x205B,
    name: "fourdotmark",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x00, // ........
      0x24, // ..X..X..
      0x00, // ........
      0x18, // ...XX...
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+205C DOTTED CROSS ===
  {
    codepoint: 0x205C,
    name: "dottedcross",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x00, // ........
      0x18, // ...XX...
      0x66, // .XX..XX.
      0x00, // ........
      0x66, // .XX..XX.
      0x18, // ...XX...
      0x00, // ........
      0x18, // ...XX...
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+205D TRICOLON ===
  // Three dots stacked vertically
  {
    codepoint: 0x205D,
    name: "tricolon",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x18, // ...XX...
      0x00, // ........
      0x18, // ...XX...
      0x18, // ...XX...
      0x00, // ........
      0x18, // ...XX...
      0x18, // ...XX...
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+205E VERTICAL FOUR DOTS ===
  {
    codepoint: 0x205E,
    name: "verticalfourdots",
    grid: hexToGrid([
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x18, // ...XX...
      0x00, // ........
      0x18, // ...XX...
      0x00, // ........
      0x18, // ...XX...
      0x00, // ........
      0x18, // ...XX...
      0x18, // ...XX...
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ]),
  },

  // === U+205F MEDIUM MATHEMATICAL SPACE ===
  { codepoint: 0x205F, name: "mediummathspace", grid: emptyGrid() },

  // === U+2060 WORD JOINER (invisible) ===
  { codepoint: 0x2060, name: "wordjoiner", grid: emptyGrid() },

  // === U+2061 FUNCTION APPLICATION (invisible) ===
  { codepoint: 0x2061, name: "functionapplication", grid: emptyGrid() },

  // === U+2062 INVISIBLE TIMES (invisible) ===
  { codepoint: 0x2062, name: "invisibletimes", grid: emptyGrid() },

  // === U+2063 INVISIBLE SEPARATOR (invisible) ===
  { codepoint: 0x2063, name: "invisibleseparator", grid: emptyGrid() },

  // === U+2064 INVISIBLE PLUS (invisible) ===
  { codepoint: 0x2064, name: "invisibleplus", grid: emptyGrid() },

  // === U+2066–U+2069: Bidi isolate formatting (invisible) ===
  { codepoint: 0x2066, name: "lefttorightisolate", grid: emptyGrid() },
  { codepoint: 0x2067, name: "righttoleftisolate", grid: emptyGrid() },
  { codepoint: 0x2068, name: "firstsstrongisolate", grid: emptyGrid() },
  { codepoint: 0x2069, name: "popdirectionalisolate", grid: emptyGrid() },

  // === U+206A–U+206F: Deprecated formatting characters (invisible) ===
  { codepoint: 0x206A, name: "inhibitsymmetricswapping", grid: emptyGrid() },
  { codepoint: 0x206B, name: "activatesymmetricswapping", grid: emptyGrid() },
  { codepoint: 0x206C, name: "inhibitarabicformshaping", grid: emptyGrid() },
  { codepoint: 0x206D, name: "activatearabicformshaping", grid: emptyGrid() },
  { codepoint: 0x206E, name: "nationdigitshapes", grid: emptyGrid() },
  { codepoint: 0x206F, name: "nominaldigitshapes", grid: emptyGrid() },
];

function gridToGlyphContent(name: string, codepoint: number, grid: boolean[][]): string {
  const cpHex = codepoint.toString(16).toUpperCase().padStart(4, "0");
  const lines: string[] = [];

  lines.push(`# ${name} (U+${cpHex})`);
  lines.push("");

  for (let r = 0; r < ROWS; r++) {
    let rowStr = "";
    for (let c = 0; c < COLS; c++) {
      rowStr += grid[r][c] ? "X" : ".";
    }
    lines.push(rowStr);
  }

  return lines.join("\n") + "\n";
}

function findExistingCodepoints(): Set<number> {
  const existing = new Set<number>();
  // Scan all subdirectories under glyphs/
  const subdirs = fs.readdirSync(GLYPHS_ROOT, { withFileTypes: true });
  for (const dirent of subdirs) {
    if (!dirent.isDirectory()) continue;
    const dirPath = path.join(GLYPHS_ROOT, dirent.name);
    const files = fs.readdirSync(dirPath);
    for (const file of files) {
      const match = file.match(/^U\+([0-9A-Fa-f]{4,6})_/);
      if (match) {
        const cp = parseInt(match[1], 16);
        if (cp >= 0x2000 && cp <= 0x206F) {
          existing.add(cp);
        }
      }
    }
  }
  return existing;
}

function main(): void {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  const existing = findExistingCodepoints();
  console.log(`Found ${existing.size} existing glyphs in U+2000–U+206F range.`);

  // Filter to only missing codepoints
  const toGenerate = glyphDefs.filter((def) => !existing.has(def.codepoint));

  if (toGenerate.length === 0) {
    console.log("All General Punctuation glyphs already exist. Nothing to generate.");
    return;
  }

  let count = 0;
  for (const def of toGenerate) {
    const cpHex = def.codepoint.toString(16).toUpperCase().padStart(4, "0");
    const filename = `U+${cpHex}_${def.name}.glyph`;
    const filePath = path.join(OUTPUT_DIR, filename);
    const content = gridToGlyphContent(def.name, def.codepoint, def.grid);
    fs.writeFileSync(filePath, content, "utf-8");
    count++;
    console.log(`  Created ${filename}`);
  }

  const total = existing.size + count;
  console.log(
    `\nGenerated ${count} new General Punctuation glyphs in ${OUTPUT_DIR}`,
  );
  console.log(`Total General Punctuation glyphs (U+2000–U+206F): ${total}/112`);
}

main();
