/**
 * Generate the ~60 missing Mathematical Operator .glyph files (U+2200–U+22FF)
 * for the Sergamon font.
 *
 * Each glyph is an 8x16 pixel grid. Baseline is at row 13.
 * Rows are encoded as hex bytes (bit 7 = leftmost pixel).
 */

import fs from "node:fs";
import path from "node:path";

const PROJECT_ROOT = path.resolve(
  path.dirname(new URL(import.meta.url).pathname),
  "..",
);
const OUTPUT_DIR = path.join(PROJECT_ROOT, "glyphs", "math");

const COLS = 8;
const ROWS = 16;

interface GlyphDef {
  codepoint: number;
  name: string;
  label: string;
  rows: number[]; // 16 hex values, bit7=leftmost
}

// Helper: convert 16 hex row values to grid strings
function rowsToGrid(hexRows: number[]): string[] {
  const lines: string[] = [];
  for (let r = 0; r < ROWS; r++) {
    let line = "";
    const val = hexRows[r] || 0;
    for (let c = 0; c < COLS; c++) {
      line += val & (0x80 >> c) ? "X" : ".";
    }
    lines.push(line);
  }
  return lines;
}

function writeGlyph(def: GlyphDef): void {
  const hex = def.codepoint.toString(16).toUpperCase().padStart(4, "0");
  const filename = `U+${hex}_${def.name}.glyph`;
  const filepath = path.join(OUTPUT_DIR, filename);

  if (fs.existsSync(filepath)) {
    console.log(`  SKIP ${filename} (already exists)`);
    return;
  }

  const grid = rowsToGrid(def.rows);
  const content = `# ${def.label} (U+${hex})\n\n${grid.join("\n")}\n`;
  fs.writeFileSync(filepath, content);
  console.log(`  WROTE ${filename}`);
}

// ─── Glyph definitions ───────────────────────────────────────────────

const glyphs: GlyphDef[] = [
  // U+2231 CLOCKWISE INTEGRAL
  {
    codepoint: 0x2231,
    name: "clockwiseintegral",
    label: "clockwise integral",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x0e, // ....XXX.
      0x18, // ...XX...
      0x18, // ...XX...
      0x18, // ...XX...
      0x18, // ...XX...
      0x1c, // ...XXX..
      0x12, // ...X..X.
      0x0c, // ....XX..
      0x18, // ...XX...
      0x18, // ...XX...
      0x18, // ...XX...
      0x18, // ...XX...
      0xe0, // XXX.....
    ],
  },
  // U+2232 CLOCKWISE CONTOUR INTEGRAL
  {
    codepoint: 0x2232,
    name: "clockwisecontourintegral",
    label: "clockwise contour integral",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x0e, // ....XXX.
      0x18, // ...XX...
      0x18, // ...XX...
      0x3c, // ..XXXX..
      0x66, // .XX..XX.
      0x6e, // .XX.XXX.
      0x62, // .XX...X.
      0x3c, // ..XXXX..
      0x18, // ...XX...
      0x18, // ...XX...
      0x18, // ...XX...
      0x18, // ...XX...
      0xe0, // XXX.....
    ],
  },
  // U+2233 ANTICLOCKWISE CONTOUR INTEGRAL
  {
    codepoint: 0x2233,
    name: "anticlockwisecontourintegral",
    label: "anticlockwise contour integral",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x0e, // ....XXX.
      0x18, // ...XX...
      0x18, // ...XX...
      0x3c, // ..XXXX..
      0x66, // .XX..XX.
      0x76, // .XXX.XX.
      0x46, // .X...XX.
      0x3c, // ..XXXX..
      0x18, // ...XX...
      0x18, // ...XX...
      0x18, // ...XX...
      0x18, // ...XX...
      0xe0, // XXX.....
    ],
  },
  // U+223B HOMOTHETIC
  {
    codepoint: 0x223b,
    name: "homothetic",
    label: "homothetic",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x18, // ...XX...
      0x00, // ........
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+223F SINE WAVE
  {
    codepoint: 0x223f,
    name: "sinewave",
    label: "sine wave",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x38, // ..XXX...
      0x44, // .X...X..
      0x44, // .X...X..
      0x82, // X.....X.
      0x82, // X.....X.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+224A ALMOST EQUAL OR EQUAL TO
  {
    codepoint: 0x224a,
    name: "almostequalofequalto",
    label: "almost equal or equal to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x00, // ........
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+224B TRIPLE TILDE
  {
    codepoint: 0x224b,
    name: "tripletilde",
    label: "triple tilde",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x00, // ........
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x00, // ........
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x00, // ........
    ],
  },
  // U+224C ALL EQUAL TO
  {
    codepoint: 0x224c,
    name: "allequalto",
    label: "all equal to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+224D EQUIVALENT TO
  {
    codepoint: 0x224d,
    name: "equivalentto",
    label: "equivalent to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x42, // .X....X.
      0x24, // ..X..X..
      0x18, // ...XX...
      0x00, // ........
      0x18, // ...XX...
      0x24, // ..X..X..
      0x42, // .X....X.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+224E GEOMETRICALLY EQUIVALENT TO
  {
    codepoint: 0x224e,
    name: "geometricallyequivalentto",
    label: "geometrically equivalent to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x24, // ..X..X..
      0x42, // .X....X.
      0x00, // ........
      0x42, // .X....X.
      0x24, // ..X..X..
      0x18, // ...XX...
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+224F DIFFERENCE BETWEEN
  {
    codepoint: 0x224f,
    name: "differencebetween",
    label: "difference between",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x24, // ..X..X..
      0x42, // .X....X.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+225A EQUIANGULAR TO
  {
    codepoint: 0x225a,
    name: "equiangularto",
    label: "equiangular to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x24, // ..X..X..
      0x42, // .X....X.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+225B STAR EQUALS
  {
    codepoint: 0x225b,
    name: "starequals",
    label: "star equals",
    rows: [
      0x00, // ........
      0x00, // ........
      0x10, // ...X....
      0x10, // ...X....
      0xd6, // XX.X.XX.
      0x38, // ..XXX...
      0x6c, // .XX.XX..
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+225E MEASURED BY
  {
    codepoint: 0x225e,
    name: "measuredby",
    label: "measured by",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x24, // ..X..X..
      0x24, // ..X..X..
      0x18, // ...XX...
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+2279 NEITHER GREATER-THAN NOR LESS-THAN
  {
    codepoint: 0x2279,
    name: "neithergreaterlesshan",
    label: "neither greater-than nor less-than",
    rows: [
      0x00, // ........
      0x00, // ........
      0x02, // ......X.
      0x04, // .....X..
      0x06, // .....XX.
      0x68, // .XX.X...
      0x30, // ..XX....
      0x58, // .X.XX...
      0xac, // X.X.XX..
      0x16, // ...X.XX.
      0x0b, // ....X.XX (truncated to 8 bits)
      0x18, // ...XX...
      0x30, // ..XX....
      0x40, // .X......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+227C PRECEDES OR EQUAL TO
  {
    codepoint: 0x227c,
    name: "precedesorequal",
    label: "precedes or equal to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x06, // .....XX.
      0x18, // ...XX...
      0x60, // .XX.....
      0x80, // X.......
      0x60, // .XX.....
      0x18, // ...XX...
      0x06, // .....XX.
      0x00, // ........
      0xfe, // XXXXXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+227D SUCCEEDS OR EQUAL TO
  {
    codepoint: 0x227d,
    name: "succeedsorequal",
    label: "succeeds or equal to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0xc0, // XX......
      0x30, // ..XX....
      0x0c, // ....XX..
      0x02, // ......X.
      0x0c, // ....XX..
      0x30, // ..XX....
      0xc0, // XX......
      0x00, // ........
      0xfe, // XXXXXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+227E PRECEDES OR EQUIVALENT TO
  {
    codepoint: 0x227e,
    name: "precedesorequivalent",
    label: "precedes or equivalent to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x06, // .....XX.
      0x18, // ...XX...
      0x60, // .XX.....
      0x80, // X.......
      0x60, // .XX.....
      0x18, // ...XX...
      0x06, // .....XX.
      0x00, // ........
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+227F SUCCEEDS OR EQUIVALENT TO
  {
    codepoint: 0x227f,
    name: "succeedsorequivalent",
    label: "succeeds or equivalent to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0xc0, // XX......
      0x30, // ..XX....
      0x0c, // ....XX..
      0x02, // ......X.
      0x0c, // ....XX..
      0x30, // ..XX....
      0xc0, // XX......
      0x00, // ........
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+2280 DOES NOT PRECEDE
  {
    codepoint: 0x2280,
    name: "doesnotprecede",
    label: "does not precede",
    rows: [
      0x00, // ........
      0x00, // ........
      0x02, // ......X.
      0x04, // .....X..
      0x0e, // ....XXX.
      0x18, // ...XX...
      0x68, // .XX.X...
      0x90, // X..X....
      0x60, // .XX.....
      0x18, // ...XX...
      0x06, // .....XX.
      0x08, // ....X...
      0x10, // ...X....
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+2281 DOES NOT SUCCEED
  {
    codepoint: 0x2281,
    name: "doesnotsucceed",
    label: "does not succeed",
    rows: [
      0x00, // ........
      0x00, // ........
      0x02, // ......X.
      0x04, // .....X..
      0xc8, // XX..X...
      0x30, // ..XX....
      0x1c, // ...XXX..
      0x0a, // ....X.X.
      0x0c, // ....XX..
      0x30, // ..XX....
      0xc0, // XX......
      0x08, // ....X...
      0x10, // ...X....
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+228C MULTISET
  {
    codepoint: 0x228c,
    name: "multiset",
    label: "multiset",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x3e, // ..XXXXX.
      0x60, // .XX.....
      0x60, // .XX.....
      0xf8, // XXXXX...
      0x60, // .XX.....
      0x60, // .XX.....
      0x3e, // ..XXXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+228D MULTISET MULTIPLICATION
  {
    codepoint: 0x228d,
    name: "multisetmultiplication",
    label: "multiset multiplication",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x3e, // ..XXXXX.
      0x60, // .XX.....
      0xe4, // XXX..X..
      0xd8, // XX.XX...
      0xe4, // XXX..X..
      0x60, // .XX.....
      0x3e, // ..XXXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+228F IMAGE OF (square subset)
  {
    codepoint: 0x228f,
    name: "squaresubset",
    label: "square image of",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x60, // .XX.....
      0x60, // .XX.....
      0x60, // .XX.....
      0x60, // .XX.....
      0x60, // .XX.....
      0x7e, // .XXXXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22AF NOT DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE
  {
    codepoint: 0x22af,
    name: "notdoubleturnstile",
    label: "not double vertical bar double right turnstile",
    rows: [
      0x00, // ........
      0x00, // ........
      0x02, // ......X.
      0xd8, // XX.XX...
      0xdc, // XX.XXX..
      0xd8, // XX.XX...
      0xd8, // XX.XX...
      0xde, // XX.XXXX.
      0xd8, // XX.XX...
      0xd8, // XX.XX...
      0xdc, // XX.XXX..
      0xd8, // XX.XX...
      0x10, // ...X....
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22B0 PRECEDES UNDER RELATION
  {
    codepoint: 0x22b0,
    name: "precedesunder",
    label: "precedes under relation",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x06, // .....XX.
      0x18, // ...XX...
      0x60, // .XX.....
      0x80, // X.......
      0x60, // .XX.....
      0x18, // ...XX...
      0x06, // .....XX.
      0x00, // ........
      0x80, // X.......
      0x60, // .XX.....
      0x18, // ...XX...
      0x06, // .....XX.
      0x00, // ........
    ],
  },
  // U+22B1 SUCCEEDS UNDER RELATION
  {
    codepoint: 0x22b1,
    name: "succeedsunder",
    label: "succeeds under relation",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0xc0, // XX......
      0x30, // ..XX....
      0x0c, // ....XX..
      0x02, // ......X.
      0x0c, // ....XX..
      0x30, // ..XX....
      0xc0, // XX......
      0x00, // ........
      0x02, // ......X.
      0x0c, // ....XX..
      0x30, // ..XX....
      0xc0, // XX......
      0x00, // ........
    ],
  },
  // U+22D5 EQUAL AND PARALLEL TO
  {
    codepoint: 0x22d5,
    name: "equalandparallel",
    label: "equal and parallel to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x66, // .XX..XX.
      0x66, // .XX..XX.
      0x66, // .XX..XX.
      0x66, // .XX..XX.
      0x66, // .XX..XX.
      0x66, // .XX..XX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22DC EQUAL TO OR LESS-THAN
  {
    codepoint: 0x22dc,
    name: "equalorlessthan",
    label: "equal to or less-than",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x06, // .....XX.
      0x18, // ...XX...
      0x60, // .XX.....
      0x80, // X.......
      0x60, // .XX.....
      0x18, // ...XX...
      0x06, // .....XX.
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22DD EQUAL TO OR GREATER-THAN
  {
    codepoint: 0x22dd,
    name: "equalorgreaterthan",
    label: "equal to or greater-than",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0xc0, // XX......
      0x30, // ..XX....
      0x0c, // ....XX..
      0x02, // ......X.
      0x0c, // ....XX..
      0x30, // ..XX....
      0xc0, // XX......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22DE EQUAL TO OR PRECEDES
  {
    codepoint: 0x22de,
    name: "equalorprecedes",
    label: "equal to or precedes",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x06, // .....XX.
      0x18, // ...XX...
      0x60, // .XX.....
      0x80, // X.......
      0x60, // .XX.....
      0x18, // ...XX...
      0x06, // .....XX.
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22DF EQUAL TO OR SUCCEEDS
  {
    codepoint: 0x22df,
    name: "equalorsucceeds",
    label: "equal to or succeeds",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0xc0, // XX......
      0x30, // ..XX....
      0x0c, // ....XX..
      0x02, // ......X.
      0x0c, // ....XX..
      0x30, // ..XX....
      0xc0, // XX......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22E1 DOES NOT SUCCEED OR EQUAL
  {
    codepoint: 0x22e1,
    name: "doesnotsucceedorequal",
    label: "does not succeed or equal",
    rows: [
      0x00, // ........
      0x02, // ......X.
      0x04, // .....X..
      0xc8, // XX..X...
      0x30, // ..XX....
      0x0c, // ....XX..
      0x02, // ......X.
      0x0c, // ....XX..
      0x30, // ..XX....
      0xc0, // XX......
      0x08, // ....X...
      0xfe, // XXXXXXX.
      0x20, // ..X.....
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22E2 NOT SQUARE IMAGE OF OR EQUAL TO
  {
    codepoint: 0x22e2,
    name: "notsquareimageorequal",
    label: "not square image of or equal to",
    rows: [
      0x00, // ........
      0x02, // ......X.
      0x04, // .....X..
      0x7c, // .XXXXX..
      0x68, // .XX.X...
      0x60, // .XX.....
      0x60, // .XX.....
      0x60, // .XX.....
      0x60, // .XX.....
      0x7e, // .XXXXXX.
      0x10, // ...X....
      0x7e, // .XXXXXX.
      0x20, // ..X.....
      0x40, // .X......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22E3 NOT SQUARE ORIGINAL OF OR EQUAL TO
  {
    codepoint: 0x22e3,
    name: "notsquareoriginalorequal",
    label: "not square original of or equal to",
    rows: [
      0x00, // ........
      0x02, // ......X.
      0x04, // .....X..
      0x7c, // .XXXXX..
      0x0c, // ....XX..
      0x0c, // ....XX..
      0x0c, // ....XX..
      0x0c, // ....XX..
      0x0c, // ....XX..
      0x7e, // .XXXXXX.
      0x10, // ...X....
      0x7e, // .XXXXXX.
      0x20, // ..X.....
      0x40, // .X......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22E4 SQUARE IMAGE OF OR NOT EQUAL TO
  {
    codepoint: 0x22e4,
    name: "squareimagenotequal",
    label: "square image of or not equal to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x60, // .XX.....
      0x60, // .XX.....
      0x60, // .XX.....
      0x60, // .XX.....
      0x60, // .XX.....
      0x7e, // .XXXXXX.
      0x04, // .....X..
      0x7e, // .XXXXXX.
      0x10, // ...X....
      0x7e, // .XXXXXX.
      0x40, // .X......
      0x00, // ........
    ],
  },
  // U+22E5 SQUARE ORIGINAL OF OR NOT EQUAL TO
  {
    codepoint: 0x22e5,
    name: "squareoriginalnotequal",
    label: "square original of or not equal to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x06, // .....XX.
      0x06, // .....XX.
      0x06, // .....XX.
      0x06, // .....XX.
      0x06, // .....XX.
      0x7e, // .XXXXXX.
      0x04, // .....X..
      0x7e, // .XXXXXX.
      0x10, // ...X....
      0x7e, // .XXXXXX.
      0x40, // .X......
      0x00, // ........
    ],
  },
  // U+22E6 LESS-THAN BUT NOT EQUIVALENT TO
  {
    codepoint: 0x22e6,
    name: "lessthannotequivalent",
    label: "less-than but not equivalent to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x06, // .....XX.
      0x18, // ...XX...
      0x60, // .XX.....
      0x80, // X.......
      0x60, // .XX.....
      0x18, // ...XX...
      0x06, // .....XX.
      0x04, // .....X..
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x40, // .X......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22E7 GREATER-THAN BUT NOT EQUIVALENT TO
  {
    codepoint: 0x22e7,
    name: "greaterthannotequivalent",
    label: "greater-than but not equivalent to",
    rows: [
      0x00, // ........
      0x00, // ........
      0xc0, // XX......
      0x30, // ..XX....
      0x0c, // ....XX..
      0x02, // ......X.
      0x0c, // ....XX..
      0x30, // ..XX....
      0xc0, // XX......
      0x04, // .....X..
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x40, // .X......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22E8 PRECEDES BUT NOT EQUIVALENT TO
  {
    codepoint: 0x22e8,
    name: "precedesnotequivalent",
    label: "precedes but not equivalent to",
    rows: [
      0x00, // ........
      0x00, // ........
      0x06, // .....XX.
      0x18, // ...XX...
      0x60, // .XX.....
      0x80, // X.......
      0x60, // .XX.....
      0x18, // ...XX...
      0x06, // .....XX.
      0x04, // .....X..
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x40, // .X......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22E9 SUCCEEDS BUT NOT EQUIVALENT TO
  {
    codepoint: 0x22e9,
    name: "succeedsnotequivalent",
    label: "succeeds but not equivalent to",
    rows: [
      0x00, // ........
      0x00, // ........
      0xc0, // XX......
      0x30, // ..XX....
      0x0c, // ....XX..
      0x02, // ......X.
      0x0c, // ....XX..
      0x30, // ..XX....
      0xc0, // XX......
      0x04, // .....X..
      0x72, // .XXX..X.
      0xda, // XX.XX.X.
      0x9c, // X..XXX..
      0x40, // .X......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22EA NOT NORMAL SUBGROUP OF
  {
    codepoint: 0x22ea,
    name: "notnormalsubgroup",
    label: "not normal subgroup of",
    rows: [
      0x00, // ........
      0x02, // ......X.
      0x04, // .....X..
      0x0c, // ....XX..
      0x18, // ...XX...
      0x30, // ..XX....
      0x68, // .XX.X...
      0xd0, // XX.X....
      0x60, // .XX.....
      0x30, // ..XX....
      0x18, // ...XX...
      0x0c, // ....XX..
      0x10, // ...X....
      0x20, // ..X.....
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22EB DOES NOT CONTAIN AS NORMAL SUBGROUP
  {
    codepoint: 0x22eb,
    name: "notcontainsnormalsubgroup",
    label: "does not contain as normal subgroup",
    rows: [
      0x00, // ........
      0x02, // ......X.
      0x04, // .....X..
      0x60, // .XX.....
      0x30, // ..XX....
      0x18, // ...XX...
      0x2c, // ..X.XX..
      0x16, // ...X.XX.
      0x0c, // ....XX..
      0x18, // ...XX...
      0x30, // ..XX....
      0x60, // .XX.....
      0x10, // ...X....
      0x20, // ..X.....
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22EC NOT NORMAL SUBGROUP OF OR EQUAL TO
  {
    codepoint: 0x22ec,
    name: "notnormalsubgrouporequal",
    label: "not normal subgroup of or equal to",
    rows: [
      0x00, // ........
      0x02, // ......X.
      0x0c, // ....XX..
      0x18, // ...XX...
      0x30, // ..XX....
      0x68, // .XX.X...
      0xd0, // XX.X....
      0x60, // .XX.....
      0x30, // ..XX....
      0x18, // ...XX...
      0x0c, // ....XX..
      0x10, // ...X....
      0xfe, // XXXXXXX.
      0x40, // .X......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22ED DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL
  {
    codepoint: 0x22ed,
    name: "notcontainsnormalsubgrouporequal",
    label: "does not contain as normal subgroup or equal",
    rows: [
      0x00, // ........
      0x02, // ......X.
      0x64, // .XX..X..
      0x30, // ..XX....
      0x18, // ...XX...
      0x2c, // ..X.XX..
      0x16, // ...X.XX.
      0x0c, // ....XX..
      0x18, // ...XX...
      0x30, // ..XX....
      0x60, // .XX.....
      0x10, // ...X....
      0xfe, // XXXXXXX.
      0x40, // .X......
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22F1 DOWN RIGHT DIAGONAL ELLIPSIS
  {
    codepoint: 0x22f1,
    name: "downrightdiagellipsis",
    label: "down right diagonal ellipsis",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x80, // X.......
      0x00, // ........
      0x10, // ...X....
      0x00, // ........
      0x02, // ......X.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22F2 ELEMENT OF WITH LONG HORIZONTAL STROKE
  {
    codepoint: 0x22f2,
    name: "elementoflongstroke",
    label: "element of with long horizontal stroke",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x1e, // ...XXXX.
      0x30, // ..XX....
      0x60, // .XX.....
      0xfe, // XXXXXXX.
      0x60, // .XX.....
      0x30, // ..XX....
      0x1e, // ...XXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22F3 ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
  {
    codepoint: 0x22f3,
    name: "elementofvertbar",
    label: "element of with vertical bar at end",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x02, // ......X.
      0x1e, // ...XXXX.
      0x32, // ..XX..X.
      0x62, // .XX...X.
      0xfe, // XXXXXXX.
      0x62, // .XX...X.
      0x32, // ..XX..X.
      0x1e, // ...XXXX.
      0x02, // ......X.
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22F4 SMALL ELEMENT OF WITH VERTICAL BAR AT END
  {
    codepoint: 0x22f4,
    name: "smallelementofvertbar",
    label: "small element of with vertical bar at end",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x02, // ......X.
      0x1e, // ...XXXX.
      0x32, // ..XX..X.
      0xfe, // XXXXXXX.
      0x32, // ..XX..X.
      0x1e, // ...XXXX.
      0x02, // ......X.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22F5 ELEMENT OF WITH DOT ABOVE
  {
    codepoint: 0x22f5,
    name: "elementofdotabove",
    label: "element of with dot above",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x18, // ...XX...
      0x18, // ...XX...
      0x00, // ........
      0x1e, // ...XXXX.
      0x30, // ..XX....
      0x60, // .XX.....
      0xfc, // XXXXXX..
      0x60, // .XX.....
      0x30, // ..XX....
      0x1e, // ...XXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22F6 ELEMENT OF WITH OVERBAR
  {
    codepoint: 0x22f6,
    name: "elementofoverbar",
    label: "element of with overbar",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x1e, // ...XXXX.
      0x30, // ..XX....
      0x60, // .XX.....
      0xfc, // XXXXXX..
      0x60, // .XX.....
      0x30, // ..XX....
      0x1e, // ...XXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22F7 SMALL ELEMENT OF WITH OVERBAR
  {
    codepoint: 0x22f7,
    name: "smallelementofoverbar",
    label: "small element of with overbar",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x1e, // ...XXXX.
      0x30, // ..XX....
      0xfc, // XXXXXX..
      0x30, // ..XX....
      0x1e, // ...XXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22F8 ELEMENT OF WITH UNDERBAR
  {
    codepoint: 0x22f8,
    name: "elementofunderbar",
    label: "element of with underbar",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x1e, // ...XXXX.
      0x30, // ..XX....
      0x60, // .XX.....
      0xfc, // XXXXXX..
      0x60, // .XX.....
      0x30, // ..XX....
      0x1e, // ...XXXX.
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22F9 ELEMENT OF WITH TWO HORIZONTAL STROKES
  {
    codepoint: 0x22f9,
    name: "elementoftwostroke",
    label: "element of with two horizontal strokes",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x1e, // ...XXXX.
      0x30, // ..XX....
      0x60, // .XX.....
      0xfc, // XXXXXX..
      0x60, // .XX.....
      0xfc, // XXXXXX..
      0x60, // .XX.....
      0x30, // ..XX....
      0x1e, // ...XXXX.
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22FA CONTAINS WITH LONG HORIZONTAL STROKE
  {
    codepoint: 0x22fa,
    name: "containslongstroke",
    label: "contains with long horizontal stroke",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0xf0, // XXXX....
      0x18, // ...XX...
      0x0c, // ....XX..
      0xfe, // XXXXXXX.
      0x0c, // ....XX..
      0x18, // ...XX...
      0xf0, // XXXX....
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22FB CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
  {
    codepoint: 0x22fb,
    name: "containsvertbar",
    label: "contains with vertical bar at end",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x80, // X.......
      0xf0, // XXXX....
      0x98, // X..XX...
      0x8c, // X...XX..
      0xfe, // XXXXXXX.
      0x8c, // X...XX..
      0x98, // X..XX...
      0xf0, // XXXX....
      0x80, // X.......
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22FC SMALL CONTAINS WITH VERTICAL BAR AT END
  {
    codepoint: 0x22fc,
    name: "smallcontainsvertbar",
    label: "small contains with vertical bar at end",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x80, // X.......
      0xf0, // XXXX....
      0x98, // X..XX...
      0xfe, // XXXXXXX.
      0x98, // X..XX...
      0xf0, // XXXX....
      0x80, // X.......
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22FD CONTAINS WITH OVERBAR
  {
    codepoint: 0x22fd,
    name: "containsoverbar",
    label: "contains with overbar",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0xf0, // XXXX....
      0x18, // ...XX...
      0x0c, // ....XX..
      0x7e, // .XXXXXX.
      0x0c, // ....XX..
      0x18, // ...XX...
      0xf0, // XXXX....
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22FE SMALL CONTAINS WITH OVERBAR
  {
    codepoint: 0x22fe,
    name: "smallcontainsoverbar",
    label: "small contains with overbar",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x7e, // .XXXXXX.
      0x00, // ........
      0xf0, // XXXX....
      0x18, // ...XX...
      0x7e, // .XXXXXX.
      0x18, // ...XX...
      0xf0, // XXXX....
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
    ],
  },
  // U+22FF Z NOTATION BAG MEMBERSHIP
  {
    codepoint: 0x22ff,
    name: "bagmembership",
    label: "z notation bag membership",
    rows: [
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x00, // ........
      0x1e, // ...XXXX.
      0x30, // ..XX....
      0x60, // .XX.....
      0xfc, // XXXXXX..
      0x60, // .XX.....
      0x30, // ..XX....
      0x1e, // ...XXXX.
      0x00, // ........
      0x04, // .....X..
      0x0c, // ....XX..
      0x00, // ........
    ],
  },
];

// ─── Main ─────────────────────────────────────────────────────────────

function main(): void {
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  console.log(
    `Generating ${glyphs.length} missing math operator glyphs in ${OUTPUT_DIR}`,
  );

  let written = 0;
  let skipped = 0;
  for (const g of glyphs) {
    const hex = g.codepoint.toString(16).toUpperCase().padStart(4, "0");
    const filename = `U+${hex}_${g.name}.glyph`;
    const filepath = path.join(OUTPUT_DIR, filename);
    if (fs.existsSync(filepath)) {
      skipped++;
      console.log(`  SKIP ${filename} (already exists)`);
    } else {
      writeGlyph(g);
      written++;
    }
  }
  console.log(`Done: ${written} written, ${skipped} skipped`);
}

main();
